# Generated by Django 4.2.18 on 2025-01-24 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='city',
        ),
    ]
