# Generated by Django 4.2.18 on 2025-01-28 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0002_remove_recipe_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('id_recipe', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='favoris', to='recipe_app.recipe')),
            ],
        ),
    ]
